//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XapDeployer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XapDeployer.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string GenreApp {
            get {
                return ResourceManager.GetString("GenreApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string GenreGame {
            get {
                return ResourceManager.GetString("GenreGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string ID_CAP_APPOINTMENTS {
            get {
                return ResourceManager.GetString("ID_CAP_APPOINTMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string ID_CAP_CAMERA {
            get {
                return ResourceManager.GetString("ID_CAP_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string ID_CAP_CONTACTS {
            get {
                return ResourceManager.GetString("ID_CAP_CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File viewing.
        /// </summary>
        public static string ID_CAP_FILEVIEWER {
            get {
                return ResourceManager.GetString("ID_CAP_FILEVIEWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xbox Live.
        /// </summary>
        public static string ID_CAP_GAMERSERVICES {
            get {
                return ResourceManager.GetString("ID_CAP_GAMERSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device identification.
        /// </summary>
        public static string ID_CAP_IDENTITY_DEVICE {
            get {
                return ResourceManager.GetString("ID_CAP_IDENTITY_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User identification.
        /// </summary>
        public static string ID_CAP_IDENTITY_USER {
            get {
                return ResourceManager.GetString("ID_CAP_IDENTITY_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interop services.
        /// </summary>
        public static string ID_CAP_INTEROPSERVICES {
            get {
                return ResourceManager.GetString("ID_CAP_INTEROPSERVICES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string ID_CAP_ISV_CAMERA {
            get {
                return ResourceManager.GetString("ID_CAP_ISV_CAMERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services.
        /// </summary>
        public static string ID_CAP_LOCATION {
            get {
                return ResourceManager.GetString("ID_CAP_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia library.
        /// </summary>
        public static string ID_CAP_MEDIALIB {
            get {
                return ResourceManager.GetString("ID_CAP_MEDIALIB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microphone.
        /// </summary>
        public static string ID_CAP_MICROPHONE {
            get {
                return ResourceManager.GetString("ID_CAP_MICROPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking.
        /// </summary>
        public static string ID_CAP_NETWORKING {
            get {
                return ResourceManager.GetString("ID_CAP_NETWORKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking setup.
        /// </summary>
        public static string ID_CAP_NETWORKING_ADMIN {
            get {
                return ResourceManager.GetString("ID_CAP_NETWORKING_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OEM.
        /// </summary>
        public static string ID_CAP_OEMPUBLICDIRECTORY {
            get {
                return ResourceManager.GetString("ID_CAP_OEMPUBLICDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string ID_CAP_PHONEDIALER {
            get {
                return ResourceManager.GetString("ID_CAP_PHONEDIALER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push-notfications.
        /// </summary>
        public static string ID_CAP_PUSH_NOTIFICATION {
            get {
                return ResourceManager.GetString("ID_CAP_PUSH_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringtones.
        /// </summary>
        public static string ID_CAP_RINGTONE_ADD {
            get {
                return ResourceManager.GetString("ID_CAP_RINGTONE_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensors.
        /// </summary>
        public static string ID_CAP_SENSORS {
            get {
                return ResourceManager.GetString("ID_CAP_SENSORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web-browser.
        /// </summary>
        public static string ID_CAP_WEBBROWSERCOMPONENT {
            get {
                return ResourceManager.GetString("ID_CAP_WEBBROWSERCOMPONENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string txtAbout {
            get {
                return ResourceManager.GetString("txtAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string txtAgree {
            get {
                return ResourceManager.GetString("txtAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already installed. Do you want to update it?.
        /// </summary>
        public static string txtAlreadyInstalled {
            get {
                return ResourceManager.GetString("txtAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate.
        /// </summary>
        public static string txtAssociate {
            get {
                return ResourceManager.GetString("txtAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string txtAuthor {
            get {
                return ResourceManager.GetString("txtAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capabilities.
        /// </summary>
        public static string txtCapabilities {
            get {
                return ResourceManager.GetString("txtCapabilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caution.
        /// </summary>
        public static string txtCaution {
            get {
                return ResourceManager.GetString("txtCaution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        public static string txtCurrentVersion {
            get {
                return ResourceManager.GetString("txtCurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string txtError {
            get {
                return ResourceManager.GetString("txtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string txtFileBrowser {
            get {
                return ResourceManager.GetString("txtFileBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is signed, therefore it cannot be installed. Try to search for that application in Marketplace.
        /// </summary>
        public static string txtFileIsSigned {
            get {
                return ResourceManager.GetString("txtFileIsSigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string txtFileSize {
            get {
                return ResourceManager.GetString("txtFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string txtGenre {
            get {
                return ResourceManager.GetString("txtGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use built-in File Browser or any third party file explorer to install XAP files..
        /// </summary>
        public static string txtGreeting {
            get {
                return ResourceManager.GetString("txtGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate deployer with XAP files to add a possibility to open XAP files using any file explorer or browser.
        /// </summary>
        public static string txtGreetingAssociate {
            get {
                return ResourceManager.GetString("txtGreetingAssociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and code snippets by Heathcliff74.
        /// </summary>
        public static string txtHeathcliffSnippets {
            get {
                return ResourceManager.GetString("txtHeathcliffSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string txtInstall {
            get {
                return ResourceManager.GetString("txtInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install all.
        /// </summary>
        public static string txtInstallAll {
            get {
                return ResourceManager.GetString("txtInstallAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed.
        /// </summary>
        public static string txtInstallationCompleted {
            get {
                return ResourceManager.GetString("txtInstallationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) installed
        ///{1} file(s) skipped
        ///{2} file(s) couldn&apos;t be installed because of error.
        /// </summary>
        public static string txtInstallationCompletedReport {
            get {
                return ResourceManager.GetString("txtInstallationCompletedReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAP Deployer is still processing this application. If you close deployment window, operation will proceed in background but you will stop seeing an actual progress.
        ///If you really want to continue, press &quot;OK&quot;..
        /// </summary>
        public static string txtInstallationInProgress {
            get {
                return ResourceManager.GetString("txtInstallationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string txtInstalled {
            get {
                return ResourceManager.GetString("txtInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error occured while installing an application.
        /// </summary>
        public static string txtInstallError {
            get {
                return ResourceManager.GetString("txtInstallError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string txtInstalling {
            get {
                return ResourceManager.GetString("txtInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limitation of Liability. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MODIFIES AND/OR CONVEYS THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERAT [rest of string was truncated]&quot;;.
        /// </summary>
        public static string txtLicenseResponsibility {
            get {
                return ResourceManager.GetString("txtLicenseResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAP Deployer - non-commercial project. It is provided AS IS without any warranties. Author isn&apos;t responsible for any damage to your device and your data..
        /// </summary>
        public static string txtLicenseShort {
            get {
                return ResourceManager.GetString("txtLicenseShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer of Warranty. THERE IS NO WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR OTHER PARTIES PROVIDE THE PROGRAM “AS IS” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE, YOU ASSUME T [rest of string was truncated]&quot;;.
        /// </summary>
        public static string txtLicenseWarranty {
            get {
                return ResourceManager.GetString("txtLicenseWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading file....
        /// </summary>
        public static string txtLoading {
            get {
                return ResourceManager.GetString("txtLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALLING APPLICATIONS.
        /// </summary>
        public static string txtMultiInstall {
            get {
                return ResourceManager.GetString("txtMultiInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caution! 
        ///XAP Deployer cannot check native EXE for viruses and other possible harm. Make sure application was downloaded from a trusted source.
        ///If you&apos;re not sure, don&apos;t run it..
        /// </summary>
        public static string txtNativeWarning {
            get {
                return ResourceManager.GetString("txtNativeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        public static string txtNewVersion {
            get {
                return ResourceManager.GetString("txtNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string txtNo {
            get {
                return ResourceManager.GetString("txtNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have root access set up for this application. You can do this by using Full Unlocked ROMs or WP7 Root Tools by Heathcliff74.
        /// </summary>
        public static string txtNoRootAccess {
            get {
                return ResourceManager.GetString("txtNoRootAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not stated.
        /// </summary>
        public static string txtNotStated {
            get {
                return ResourceManager.GetString("txtNotStated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// </summary>
        public static string txtPageAboutDevoted {
            get {
                return ResourceManager.GetString("txtPageAboutDevoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following free libraries are used:.
        /// </summary>
        public static string txtPageAboutFreeLibraries {
            get {
                return ResourceManager.GetString("txtPageAboutFreeLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to their authors and maintainers!.
        /// </summary>
        public static string txtPageAboutFreeLibrariesThanks {
            get {
                return ResourceManager.GetString("txtPageAboutFreeLibrariesThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application is provided &quot;AS IS&quot; without any warranties. Author isn&apos;t responsible for any damage caused by application usage.
        /// </summary>
        public static string txtPageAboutNotice {
            get {
                return ResourceManager.GetString("txtPageAboutNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, note:.
        /// </summary>
        public static string txtPageAboutPleaseNote {
            get {
                return ResourceManager.GetString("txtPageAboutPleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more....
        /// </summary>
        public static string txtPageAboutReadMore {
            get {
                return ResourceManager.GetString("txtPageAboutReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string txtPageAboutTitle {
            get {
                return ResourceManager.GetString("txtPageAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string txtPublisher {
            get {
                return ResourceManager.GetString("txtPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string txtRun {
            get {
                return ResourceManager.GetString("txtRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not run this EXE file..
        /// </summary>
        public static string txtRunExeError {
            get {
                return ResourceManager.GetString("txtRunExeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution completed..
        /// </summary>
        public static string txtRunExeOk {
            get {
                return ResourceManager.GetString("txtRunExeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XAP / EXE / EXE7.
        /// </summary>
        public static string txtSelectXap {
            get {
                return ResourceManager.GetString("txtSelectXap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string txtSignature {
            get {
                return ResourceManager.GetString("txtSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not present.
        /// </summary>
        public static string txtSignatureMissed {
            get {
                return ResourceManager.GetString("txtSignatureMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string txtSignaturePresent {
            get {
                return ResourceManager.GetString("txtSignaturePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks:.
        /// </summary>
        public static string txtSpecialThanks {
            get {
                return ResourceManager.GetString("txtSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string txtStateFailed {
            get {
                return ResourceManager.GetString("txtStateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation pending.
        /// </summary>
        public static string txtStateInstallationPending {
            get {
                return ResourceManager.GetString("txtStateInstallationPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string txtStateInstalled {
            get {
                return ResourceManager.GetString("txtStateInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing....
        /// </summary>
        public static string txtStateInstalling {
            get {
                return ResourceManager.GetString("txtStateInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        public static string txtStateSkipped {
            get {
                return ResourceManager.GetString("txtStateSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove association.
        /// </summary>
        public static string txtUnassociate {
            get {
                return ResourceManager.GetString("txtUnassociate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string txtUninstall {
            get {
                return ResourceManager.GetString("txtUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unintalling....
        /// </summary>
        public static string txtUninstalling {
            get {
                return ResourceManager.GetString("txtUninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to uninstall this application?.
        /// </summary>
        public static string txtUninstallWarning {
            get {
                return ResourceManager.GetString("txtUninstallWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string txtUpdate {
            get {
                return ResourceManager.GetString("txtUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string txtUpdating {
            get {
                return ResourceManager.GetString("txtUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string txtVersion {
            get {
                return ResourceManager.GetString("txtVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string txtWarning {
            get {
                return ResourceManager.GetString("txtWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App installation.
        /// </summary>
        public static string txtXapDeployerTitle {
            get {
                return ResourceManager.GetString("txtXapDeployerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string txtYes {
            get {
                return ResourceManager.GetString("txtYes", resourceCulture);
            }
        }
    }
}
